/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "CloudNOS",
  "tagline": "Realize intelligent management of data center facilities.",
  "trailingSlash": true,
  "url": "https://www.cloudnos.com",
  "baseUrl": "/",
  "organizationName": "cloudnos",
  "projectName": "cloudnos",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    "docusaurus-plugin-matomo",
    "@docusaurus/theme-mermaid",
    [
      "./custom-blog-plugin",
      {
        "id": "blog",
        "routeBasePath": "blog",
        "path": "./blog"
      }
    ],
    [
      "@docusaurus/plugin-ideal-image",
      {
        "quality": 70,
        "max": 1030,
        "min": 640,
        "steps": 2,
        "disableInDev": false
      }
    ],
    [
      "content-docs",
      {
        "id": "guides",
        "path": "guides",
        "routeBasePath": "guides",
        "editCurrentVersion": true,
        "sidebarPath": "./sidebar-guides.ts",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true
      }
    ],
    [
      "posthog-docusaurus",
      {
        "apiKey": "phc_EloQUW6cgfbTc0pI9c5CXElhQ4gVGRoBsrUAoakJVoQ",
        "appUrl": "https://p.glasskube.eu",
        "ui_host": "https://eu.posthog.com",
        "enableInDevelopment": false
      }
    ]
  ],
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/glasskube/glasskube/tree/main/website/"
        },
        "blog": false,
        "theme": {
          "customCss": [
            "./src/css/custom.css"
          ]
        },
        "sitemap": {
          "changefreq": "daily",
          "priority": 1,
          "ignorePatterns": [
            "/blog/archive",
            "/blog/tags",
            "/blog/tags/**"
          ],
          "filename": "sitemap.xml"
        }
      }
    ]
  ],
  "themes": [
    [
      "/Users/ktt/node/docs/giasskube/website/node_modules/@getcanary/docusaurus-theme-search-pagefind/dist/index.js",
      {
        "includeRoutes": [
          "**/*"
        ],
        "group": true,
        "tabs": [
          {
            "name": "All",
            "pattern": "**/*"
          },
          {
            "name": "Docs",
            "pattern": "/docs/**"
          },
          {
            "name": "Guides",
            "pattern": "/guides/**"
          },
          {
            "name": "Blog",
            "pattern": "/blog/**"
          }
        ]
      }
    ]
  ],
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "themeConfig": {
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "image": "https://opengraph.githubassets.com/3fbd03d4d860275ee154ca566f24ecce9243e229fe367523fbcab52e8b43db3f/glasskube/glasskube",
    "navbar": {
      "title": "CloudNOS",
      "logo": {
        "alt": "Glasskube Logo",
        "src": "img/glasskube-logo.svg"
      },
      "items": [
        {
          "sidebarId": "products",
          "label": "Products",
          "position": "left",
          "items": [
            {
              "to": "/products/DCIM",
              "label": "Cloud DCIM"
            },
            {
              "to": "/products/hub",
              "label": "Glasskube Hub (new)"
            }
          ]
        },
        {
          "to": "/pricing",
          "label": "Pricing",
          "position": "left"
        },
        {
          "sidebarId": "resources",
          "label": "Resources",
          "position": "left",
          "items": [
            {
              "type": "docSidebar",
              "sidebarId": "docs",
              "label": "Docs"
            },
            {
              "to": "/guides/cert-manager",
              "label": "Guides"
            },
            {
              "to": "/blog",
              "label": "Blog"
            }
          ]
        },
        {
          "type": "search",
          "position": "left"
        },
        {
          "type": "custom-wrapper",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Architecture",
              "to": "/docs/"
            },
            {
              "label": "Getting started",
              "to": "/docs/getting-started/install"
            }
          ]
        },
        {
          "title": "Services",
          "items": [
            {
              "label": "Integration",
              "to": "/docs/comparisons/helm"
            },
            {
              "label": "Request Demo",
              "to": "/docs/comparisons/timoni"
            },
            {
              "label": "Support Ticket",
              "to": "/docs/comparisons/olm"
            },
            {
              "label": "Client Area",
              "to": "/docs/comparisons/olm"
            }
          ]
        },
        {
          "title": "Company",
          "items": [
            {
              "label": "About Us",
              "to": "/blog"
            },
            {
              "label": "Privacy Policy",
              "to": "/roadmap"
            },
            {
              "label": "Terms of Service",
              "href": "/#"
            },
            {
              "label": "Refund Policy",
              "href": "/#"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Discord",
              "href": "/#"
            },
            {
              "label": "Twitter / X",
              "href": "/#"
            },
            {
              "label": "LinkedIn",
              "href": "/#"
            },
            {
              "label": "GitHub",
              "href": "/#"
            }
          ]
        }
      ],
      "copyright": "<br>Copyright © 2024 CloudNOS.<br>Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "matomo": {
      "matomoUrl": "https://a.glasskube.eu/",
      "siteId": "5",
      "phpLoader": "matomo.php",
      "jsLoader": "matomo.js"
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
